cp -p /home/rsholmes/Desktop/dacarduino/hardware/dacarduino/Arduino.sch ./hardware/dacarduino/Arduino.sch
cp -p /home/rsholmes/Desktop/dacarduino/hardware/dacarduino/CV_in.sch ./hardware/dacarduino/CV_in.sch
cp -p /home/rsholmes/Desktop/dacarduino/hardware/dacarduino/dacarduino.kicad_pcb ./hardware/dacarduino/dacarduino.kicad_pcb
cp -p /home/rsholmes/Desktop/dacarduino/hardware/dacarduino/dacarduino.sch ./hardware/dacarduino/dacarduino.sch
cp -p /home/rsholmes/Desktop/dacarduino/hardware/dacarduino/EurorackRSH.lib ./hardware/dacarduino/EurorackRSH.lib
cp -p /home/rsholmes/Desktop/dacarduino/hardware/dacarduino/Gate_out.sch ./hardware/dacarduino/Gate_out.sch
cp -p /home/rsholmes/Desktop/dacarduino/hardware/dacarduino/in.sch ./hardware/dacarduino/in.sch
cp -p /home/rsholmes/Desktop/dacarduino/hardware/dacarduino/power.sch ./hardware/dacarduino/power.sch
cp -p /home/rsholmes/Desktop/dacarduino/hardware/dacarduino/vref.sch ./hardware/dacarduino/vref.sch
cp -p /home/rsholmes/Desktop/dacarduino/README.md ./README.md
